apiVersion: v1
kind: ConfigMap
metadata:
  name: wowonder-nginx-config
  namespace: wowonder
data:
  default.conf: |
    server {
        listen 80;
        server_name _;
        root /var/www/html;
        index index.php index.html;

        client_max_body_size 2024M;
        client_body_timeout 5000s;
        fastcgi_read_timeout 4000s;
        fastcgi_send_timeout 4000s;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location ~* \.(css|js|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot|mp4|webm|ogg)$ {
            expires 1y;
            add_header Cache-Control "public, immutable";
            try_files $uri $uri/ =404;
        }

        location /upload/ {
            alias /var/www/html/upload/;
            expires 1y;
            add_header Cache-Control "public, immutable";
            try_files $uri $uri/ =404;
        }

        location /assets/ {
            alias /var/www/html/assets/;
            expires 1y;
            add_header Cache-Control "public";
            try_files $uri $uri/ =404;
        }

        location /themes/ {
            alias /var/www/html/themes/;
            expires 1y;
            add_header Cache-Control "public";
            try_files $uri $uri/ =404;
        }

        location /admin-panel/ {
            alias /var/www/html/admin-panel/;
            try_files $uri $uri/ /admin-panel/index.php?$query_string;
        }

        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
        }

        location ~ /\.ht {
            deny all;
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wowonder-app
  namespace: wowonder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wowonder-app
  template:
    metadata:
      labels:
        app: wowonder-app
    spec:
      nodeSelector:
        kubernetes.io/hostname: worker
      initContainers:
      - name: setup-permissions
        image: busybox:1.35
        command: ['sh', '-c', '
          echo "Setting up directories and permissions..." &&
          mkdir -p /var/www/html/upload /var/www/html/cache /var/www/html/admin-panel &&
          chown -R www-data:www-data /var/www/html &&
          chmod -R 755 /var/www/html/upload &&
          chmod -R 755 /var/www/html/cache &&
          chmod -R 755 /var/www/html/admin-panel &&
          echo "Permissions setup completed"
        ']
        volumeMounts:
        - name: upload-data
          mountPath: /var/www/html/upload
        - name: cache-data
          mountPath: /var/www/html/cache
        - name: admin-panel-data
          mountPath: /var/www/html/admin-panel
      containers:
      - name: wowonder-app
        image: $DOCKER_IMAGE:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: upload-data
          mountPath: /var/www/html/upload
        - name: cache-data
          mountPath: /var/www/html/cache
        - name: admin-panel-data
          mountPath: /var/www/html/admin-panel
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        env:
        - name: DB_HOST
          value: "mysql-service"
        - name: DB_DATABASE
          value: "wowonderdb"
        - name: DB_USERNAME
          value: "wowonderuser"
        - name: DB_PASSWORD
          value: "Password123@24"
        - name: SITE_URL
          value: "http://44.220.139.238:30080"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /index.php
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /index.php
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      volumes:
      - name: upload-data
        persistentVolumeClaim:
          claimName: wowonder-pvc
      - name: cache-data
        emptyDir: {}
      - name: admin-panel-data
        emptyDir: {}
      - name: nginx-config
        configMap:
          name: wowonder-nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: wowonder-service
  namespace: wowonder
spec:
  type: NodePort
  selector:
    app: wowonder-app
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
