apiVersion: apps/v1
kind: Deployment
metadata:
  name: wowonder-app
  namespace: wowonder
spec:
  selector:
    matchLabels:
      app: wowonder-app
  template:
    metadata:
      labels:
        app: wowonder-app
    spec:
      nodeSelector:
        kubernetes.io/hostname: worker
      containers:
      - name: wowonder-app
        image: $DOCKER_IMAGE:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: upload-data
          mountPath: /var/www/html/upload
      volumes:
      - name: upload-data
        persistentVolumeClaim:
          claimName: wowonder-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: wowonder-service
  namespace: wowonder
spec:
  type: NodePort
  selector:
    app: wowonder-app
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
