apiVersion: apps/v1
kind: Deployment
metadata:
  name: wowonder-app
  namespace: wowonder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wowonder-app
  template:
    metadata:
      labels:
        app: wowonder-app
    spec:
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ['sh', '-c', '
          mkdir -p /var/www/html/upload /var/www/html/cache /var/www/html/admin-panel &&
          chown -R www-data:www-data /var/www/html &&
          chmod -R 755 /var/www/html/upload /var/www/html/cache /var/www/html/admin-panel &&
          echo "Permissions fixed"
        ']
        volumeMounts:
        - name: upload-data
          mountPath: /var/www/html/upload
        - name: app-files
          mountPath: /var/www/html
      containers:
      - name: wowonder-app
        image: $DOCKER_IMAGE:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: upload-data
          mountPath: /var/www/html/upload
        - name: app-files
          mountPath: /var/www/html
        env:
        - name: DB_HOST
          value: "mysql-service"
        - name: DB_DATABASE
          value: "wowonderdb"
        - name: DB_USERNAME
          value: "wowonderuser"
        - name: DB_PASSWORD
          value: "Password123@24"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 5
      volumes:
      - name: upload-data
        persistentVolumeClaim:
          claimName: wowonder-pvc
      - name: app-files
        emptyDir: {}
