apiVersion: apps/v1
kind: Deployment
metadata:
  name: wowonder-app
  namespace: wowonder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wowonder-app
  template:
    metadata:
      labels:
        app: wowonder-app
    spec:
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ['sh', '-c', 'mkdir -p /var/www/html/upload && chmod -R 755 /var/www/html/upload']
        volumeMounts:
        - name: upload-data
          mountPath: /var/www/html/upload
      containers:
      - name: wowonder-app
        image: $DOCKER_IMAGE:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: upload-data
          mountPath: /var/www/html/upload
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 5
      volumes:
      - name: upload-data
        persistentVolumeClaim:
          claimName: wowonder-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: wowonder-service
  namespace: wowonder
spec:
  type: NodePort
  selector:
    app: wowonder-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
