apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: wowonder
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      nodeSelector:
        kubernetes.io/hostname: worker
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rootpassword"
        - name: MYSQL_DATABASE
          value: "wowonderdb"
        - name: MYSQL_USER
          value: "wowonderuser"
        - name: MYSQL_PASSWORD
          value: "Password123@24"
        args:
        - --default-authentication-plugin=mysql_native_password
        - --innodb-buffer-pool-size=64M
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "mysqladmin ping -uroot -prootpassword"
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "mysql -uroot -prootpassword -e 'SELECT 1'"
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: wowonder
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
